# Generated by Django 6.0.4 on 2026-04-20 08:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'CategoryMachines',
            },
        ),
        migrations.CreateModel(
            name='ProtocolLibrarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('protocol_code', models.CharField(db_column='ProtocolCode', max_length=100, unique=True)),
                ('protocol_name', models.CharField(db_column='ProtocolName', max_length=255)),
                ('form_schema_json', models.JSONField(blank=True, db_column='FormSchemaJson', null=True)),
                ('default_config_json', models.JSONField(blank=True, db_column='DefaultConfigJson', null=True)),
                ('default_worker_image', models.CharField(blank=True, db_column='DefaultWorkerImage', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ProtocolLibrarys',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('user', 'User')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_column='NormalizedName', max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='apis.departments')),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_column='NormalizedName', max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=500, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('machine_code', models.CharField(db_column='MachineCode', max_length=100, unique=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
                ('category_machine', models.ForeignKey(db_column='CategoryMachineId', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='apis.categorymachines')),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='apis.departments')),
            ],
            options={
                'db_table': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='MachineProductionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='WorkDate')),
                ('first_run_time', models.DateTimeField(blank=True, db_column='FirstRunTime', null=True)),
                ('last_run_time', models.DateTimeField(blank=True, db_column='LastRunTime', null=True)),
                ('total_run_time_in_minutes', models.IntegerField(db_column='TotalRunTimeInMinutes', default=0)),
                ('is_get_time', models.BooleanField(db_column='IsGetTime', default=False)),
                ('program_name', models.CharField(blank=True, db_column='ProgramName', max_length=255, null=True)),
                ('last_cutting_time_in_minutes', models.IntegerField(db_column='LastCuttingTimeInMinutes', default=0)),
                ('total_part', models.IntegerField(db_column='TotalPart', default=0)),
                ('machine', models.ForeignKey(db_column='MachineId', on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='apis.machines')),
            ],
            options={
                'db_table': 'MachineProductionLogs',
            },
        ),
        migrations.CreateModel(
            name='MachineProductionLogForDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='WorkDate')),
                ('program_name', models.CharField(blank=True, db_column='ProgramName', max_length=255, null=True)),
                ('first_run_time', models.DateTimeField(blank=True, db_column='FirstRunTime', null=True)),
                ('last_run_time', models.DateTimeField(blank=True, db_column='LastRunTime', null=True)),
                ('total_run_time_in_minutes', models.IntegerField(db_column='TotalRunTimeInMinutes', default=0)),
                ('error_run_time', models.IntegerField(db_column='ErrorRunTime', default=0)),
                ('total_part', models.IntegerField(db_column='TotalPart', default=0)),
                ('machine', models.ForeignKey(db_column='MachineId', on_delete=django.db.models.deletion.CASCADE, related_name='machine_production_log_for_days', to='apis.machines')),
            ],
            options={
                'db_table': 'MachineProductionLogForDays',
            },
        ),
        migrations.CreateModel(
            name='MachineLogForDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_column='WorkDate')),
                ('tag_name', models.CharField(db_column='TagName', max_length=255)),
                ('total_value', models.FloatField(db_column='TotalValue', default=0)),
                ('value_scan_for_day', models.FloatField(db_column='ValueScanForDay', default=0)),
                ('machine', models.ForeignKey(db_column='MachineId', on_delete=django.db.models.deletion.CASCADE, related_name='machine_log_for_days', to='apis.machines')),
            ],
            options={
                'db_table': 'MachineLogForDays',
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('source_name', models.CharField(db_column='SourceName', max_length=255)),
                ('polling_interval_ms', models.IntegerField(db_column='PollingIntervalMs', default=1000)),
                ('worker_service_name', models.CharField(blank=True, db_column='WorkerServiceName', max_length=255, null=True)),
                ('instance_config_json', models.JSONField(blank=True, db_column='InstanceConfigJson', null=True)),
                ('machine', models.ForeignKey(db_column='MachineId', on_delete=django.db.models.deletion.CASCADE, related_name='connection_profiles', to='apis.machines')),
                ('protocol', models.ForeignKey(db_column='ProtocolId', on_delete=django.db.models.deletion.PROTECT, related_name='connection_profiles', to='apis.protocollibrarys')),
            ],
            options={
                'db_table': 'ConnectionProfiles',
            },
        ),
        migrations.CreateModel(
            name='TagDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('deleted_date', models.DateTimeField(blank=True, db_column='DeletedDate', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DeletedBy', max_length=100, null=True)),
                ('tag_key', models.CharField(db_column='TagKey', max_length=100)),
                ('tag_name', models.CharField(db_column='TagName', max_length=255)),
                ('address_config_json', models.JSONField(blank=True, db_column='AddressConfigJson', null=True)),
                ('data_type', models.CharField(db_column='DataType', max_length=50)),
                ('scaling_factor', models.FloatField(db_column='ScalingFactor', default=1.0)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=50, null=True)),
                ('profile', models.ForeignKey(db_column='ProfileId', on_delete=django.db.models.deletion.CASCADE, related_name='tag_definitions', to='apis.connectionprofiles')),
            ],
            options={
                'db_table': 'TagDefinitions',
            },
        ),
        migrations.CreateModel(
            name='MetricValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(db_column='LogTime')),
                ('value', models.TextField(blank=True, db_column='Value', null=True)),
                ('tag', models.ForeignKey(db_column='TagId', on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='apis.tagdefinitions')),
            ],
            options={
                'db_table': 'MetricValues',
            },
        ),
        migrations.CreateModel(
            name='LiveTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='LastUpdated')),
                ('value', models.TextField(blank=True, db_column='Value', null=True)),
                ('tag', models.OneToOneField(db_column='TagId', on_delete=django.db.models.deletion.CASCADE, related_name='live_tag', to='apis.tagdefinitions')),
            ],
            options={
                'db_table': 'LiveTags',
            },
        ),
    ]
